version: '3.2'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    restart: on-failure
    environment:
      - SA_PASSWORD=pasS123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  redis:
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
