version: '3.7'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    restart: on-failure
    environment:
      - SA_PASSWORD=pasS123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  redis:
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5000:80"
    depends_on:
      - mssql
      - redis
      - elasticsearch
      - kibana